spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: jinzhou@2022
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
      timeout: 10000
opcua:
  username:
  password:
  endPointUrl: opc.tcp://192.168.0.251:49320
  requestTimeout: 10000